# The base image for AI Platform Notebook instances
FROM gcr.io/deeplearning-platform-release/tf2-gpu
# Stuff that should have been configured in the base image (bug)
ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8
# if you need additional libraries, install them like this
# RUN pip install my-library
