FROM node:16.15
WORKDIR /usr/src/app
COPY package*.json ./
RUN mkdir logs && chmod 777 logs
RUN npm install npm -g --loglevel=error
RUN npm cache clean --force --loglevel=error
RUN npm install --loglevel=error
COPY . ./
CMD [ "npm", "start" ]

