CREATE TABLE Owners (
     OwnerID STRING(36) NOT NULL, 
     OwnerName STRING(MAX) NOT NULL
) PRIMARY KEY (OwnerID);

CREATE TABLE Pets (
     PetID STRING(36) NOT NULL, 
     OwnerID STRING(36) NOT NULL, 
     PetType STRING(MAX) NOT NULL,
     PetName STRING(MAX) NOT NULL,
     Breed STRING(MAX) NOT NULL,
) PRIMARY KEY (PetID);

CREATE INDEX PetsByOwnerID ON Pets(OwnerID);
CREATE INDEX PetsByType ON Pets(PetType);
CREATE INDEX OwnersByName ON Owners(OwnerName);
CREATE INDEX Pets2ByOwnerID ON Pets2(OwnerID);