export GOOGLE_PROJECT_ID=${GOOGLE_CLOUD_PROJECT}
export APP_REGION=us-west1
export CLOUDRUN_REGION=us-west1
echo "*** configuration: GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}, APP_REGION=${APP_REGION}, CLOUDRUN_REGION=${CLOUDRUN_REGION} ***"
