export GOOGLE_PROJECT_ID=${GOOGLE_CLOUD_PROJECT}
export FIRESTORE_LOCATION=us-west1
export CLOUDRUN_REGION=us-west1
echo "*** configuration: GOOGLE_PROJECT_ID=${GOOGLE_PROJECT_ID}, FIRESTORE_LOCATION=${FIRESTORE_LOCATION}, CLOUDRUN_REGION=${CLOUDRUN_REGION} ***"
