---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shipping
  namespace: sock-shop
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: shipping

  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
    
