apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: allow-privileged-psp
spec:
  privileged: true  # Allow privileged pods!
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
  - '*' 
