kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: unrestricted-pods-role
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - allow-privileged-psp
  verbs:
  - use
