feature {
  name: "Soil_Type"
  value_count {
    min: 1
    max: 1
  }
  type: BYTES
  domain: "Soil_Type"
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Wilderness_Area"
  value_count {
    min: 1
    max: 1
  }
  type: BYTES
  domain: "Wilderness_Area"
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Aspect"
  value_count {
    min: 1
    max: 1
  }
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Cover_Type"
  value_count {
    min: 1
    max: 1
  }
  type: INT
  int_domain {
    name: "Cover_Type"
    min: 0
    max: 6
    is_categorical: true
  }
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Elevation"
  value_count {
    min: 1
    max: 1
  }
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Hillshade_3pm"
  value_count {
    min: 1
    max: 1
  }
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Hillshade_9am"
  value_count {
    min: 1
    max: 1
  }
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Hillshade_Noon"
  value_count {
    min: 1
    max: 1
  }
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Horizontal_Distance_To_Fire_Points"
  value_count {
    min: 1
    max: 1
  }
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Horizontal_Distance_To_Hydrology"
  value_count {
    min: 1
    max: 1
  }
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Horizontal_Distance_To_Roadways"
  value_count {
    min: 1
    max: 1
  }
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Slope"
  value_count {
    min: 1
    max: 1
  }
  type: INT
  int_domain {
    name: "Slope"
    min: 0
    max: 90
  }
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
feature {
  name: "Vertical_Distance_To_Hydrology"
  value_count {
    min: 1
    max: 1
  }
  type: INT
  presence {
    min_fraction: 1.0
    min_count: 1
  }
}
string_domain {
  name: "Soil_Type"
  value: "C2702"
  value: "C2703"
  value: "C2704"
  value: "C2705"
  value: "C2706"
  value: "C2717"
  value: "C3501"
  value: "C3502"
  value: "C4201"
  value: "C4703"
  value: "C4704"
  value: "C4744"
  value: "C4758"
  value: "C5101"
  value: "C5151"
  value: "C6101"
  value: "C6102"
  value: "C6731"
  value: "C7101"
  value: "C7102"
  value: "C7103"
  value: "C7201"
  value: "C7202"
  value: "C7700"
  value: "C7701"
  value: "C7702"
  value: "C7709"
  value: "C7710"
  value: "C7745"
  value: "C7746"
  value: "C7755"
  value: "C7756"
  value: "C7757"
  value: "C7790"
  value: "C8703"
  value: "C8707"
  value: "C8708"
  value: "C8771"
  value: "C8772"
  value: "C8776"
}
string_domain {
  name: "Wilderness_Area"
  value: "Cache"
  value: "Commanche"
  value: "Neota"
  value: "Rawah"
}
